name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rakudo-star:latest

    steps:
      - uses: actions/checkout@v4

      - name: Versions
        run: |
          raku -v
          zef --version || true

      - name: Install deps
        run: |
          zef install --/test --deps-only .

      - name: Run tests
        run: |
          prove -e "raku -Ilib" -r t
